[project]
name = "gamelens-collector-service"
version = "0.1.0"
description = "GameLens Data Collector Service."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=25.1.0",
    "psycopg[binary,pool]>=3.3.2",
    "python-dotenv>=1.2.1",
]
